apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwf-workspace
  namespace: nsf-maica
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: rook-cephfs
